CREATE TABLE seminar_type (
    seminar_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type_name VARCHAR(255) NOT NULL,
    description TEXT,
    duration INTEGER NOT NULL,
    arrangement_notes TEXT,
    CONSTRAINT pk_seminar_type PRIMARY KEY (seminar_type_id),
    CONSTRAINT chk_seminar_type_duration_positive CHECK (duration > 0)
);

CREATE TABLE material (
    material_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    material_name VARCHAR(255) NOT NULL,
    material_type VARCHAR(255) NOT NULL,
    description TEXT,
    unit VARCHAR(255) NOT NULL,
    CONSTRAINT pk_material PRIMARY KEY (material_id)
);

CREATE TABLE audio_visual_equipment (
    equipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    equipment_name VARCHAR(255) NOT NULL,
    equipment_type VARCHAR(255) NOT NULL,
    unit VARCHAR(255) NOT NULL,
    CONSTRAINT pk_audio_visual_equipment PRIMARY KEY (equipment_id)
);

CREATE TABLE material_requirement (
    seminar_type_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    default_quantity INTEGER NOT NULL,
    is_depend_on_num_participant BOOLEAN NOT NULL,
    participant_per_quantity INTEGER,
    notes TEXT,
    CONSTRAINT pk_material_requirement PRIMARY KEY (seminar_type_id, material_id),
    CONSTRAINT fk_material_requirement_seminar_type FOREIGN KEY (seminar_type_id)
        REFERENCES seminar_type (seminar_type_id),
    CONSTRAINT fk_material_requirement_material FOREIGN KEY (material_id)
        REFERENCES material (material_id),
    CONSTRAINT chk_material_requirement_default_quantity_positive CHECK (default_quantity > 0),
    CONSTRAINT chk_material_requirement_participant_dependency CHECK (
        (
            is_depend_on_num_participant
            AND participant_per_quantity > 0
        )
        OR (
            NOT is_depend_on_num_participant
            AND participant_per_quantity IS NULL
        )
    )
);

CREATE TABLE av_equipment_requirement (
    equipment_id BIGINT NOT NULL,
    seminar_type_id BIGINT NOT NULL,
    quantity_required INTEGER NOT NULL,
    is_depend_on_num_participant BOOLEAN NOT NULL,
    participant_per_quantity INTEGER,
    CONSTRAINT pk_av_equipment_requirement PRIMARY KEY (equipment_id, seminar_type_id),
    CONSTRAINT fk_av_equipment_requirement_equipment FOREIGN KEY (equipment_id)
        REFERENCES audio_visual_equipment (equipment_id),
    CONSTRAINT fk_av_equipment_requirement_seminar_type FOREIGN KEY (seminar_type_id)
        REFERENCES seminar_type (seminar_type_id),
    CONSTRAINT chk_av_equipment_requirement_quantity_required_positive CHECK (quantity_required > 0),
    CONSTRAINT chk_av_equipment_requirement_participant_dependency CHECK (
        (
            is_depend_on_num_participant
            AND participant_per_quantity > 0
        )
        OR (
            NOT is_depend_on_num_participant
            AND participant_per_quantity IS NULL
        )
    )
);

CREATE INDEX idx_seminar_type_type_name
    ON seminar_type (type_name);

CREATE INDEX idx_material_material_type
    ON material (material_type);

CREATE INDEX idx_audio_visual_equipment_equipment_type
    ON audio_visual_equipment (equipment_type);

CREATE INDEX idx_material_requirement_material_id
    ON material_requirement (material_id);

CREATE INDEX idx_av_equipment_requirement_seminar_type_id
    ON av_equipment_requirement (seminar_type_id);
