CREATE TABLE consultant (
    consultant_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    email VARCHAR(255),
    address TEXT,
    city VARCHAR(255),
    country VARCHAR(255),
    work VARCHAR(255),
    CONSTRAINT pk_consultant PRIMARY KEY (consultant_id)
);

CREATE TABLE seminar (
    seminar_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seminar_type_id BIGINT NOT NULL,
    consultant_id BIGINT NOT NULL,
    booking_department_user_id BIGINT NOT NULL,
    employee_id BIGINT,
    seminar_name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    city VARCHAR(255) NOT NULL,
    anticipated_registrants INTEGER NOT NULL,
    booking_created_date DATE NOT NULL,
    note TEXT,
    CONSTRAINT pk_seminar PRIMARY KEY (seminar_id),
    CONSTRAINT fk_seminar_seminar_type FOREIGN KEY (seminar_type_id)
        REFERENCES seminar_type (seminar_type_id),
    CONSTRAINT fk_seminar_consultant FOREIGN KEY (consultant_id)
        REFERENCES consultant (consultant_id),
    CONSTRAINT fk_seminar_booking_department_user FOREIGN KEY (booking_department_user_id)
        REFERENCES users (id),
    CONSTRAINT fk_seminar_employee FOREIGN KEY (employee_id)
        REFERENCES users (id),
    CONSTRAINT chk_seminar_anticipated_registrants_positive CHECK (anticipated_registrants > 0),
    CONSTRAINT chk_seminar_date_order CHECK (end_date >= start_date)
);

CREATE INDEX idx_consultant_full_name
    ON consultant (full_name);

CREATE INDEX idx_seminar_seminar_type_id
    ON seminar (seminar_type_id);

CREATE INDEX idx_seminar_consultant_id
    ON seminar (consultant_id);

CREATE INDEX idx_seminar_booking_department_user_id
    ON seminar (booking_department_user_id);

CREATE INDEX idx_seminar_employee_id
    ON seminar (employee_id);

CREATE INDEX idx_seminar_start_date
    ON seminar (start_date);
