CREATE TABLE material_request (
    material_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seminar_id BIGINT NOT NULL,
    contract_id BIGINT,
    request_date DATE NOT NULL,
    needed_by_date DATE NOT NULL,
    shipment_status VARCHAR(50) NOT NULL,
    delivered_confirmed_at TIMESTAMP,
    delivery_confirmation_note TEXT,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_material_request PRIMARY KEY (material_request_id),
    CONSTRAINT fk_material_request_seminar FOREIGN KEY (seminar_id)
        REFERENCES seminar (seminar_id),
    CONSTRAINT chk_material_request_date_order CHECK (needed_by_date >= request_date),
    CONSTRAINT chk_material_request_shipment_status CHECK (
        shipment_status IN ('REQUESTED', 'PACKED', 'SHIPPED', 'DELIVERED')
    )
);

CREATE TABLE material_request_item (
    material_request_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    requested_quantity INTEGER NOT NULL,
    notes TEXT,
    CONSTRAINT pk_material_request_item PRIMARY KEY (material_request_id, material_id),
    CONSTRAINT fk_material_request_item_request FOREIGN KEY (material_request_id)
        REFERENCES material_request (material_request_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_material_request_item_material FOREIGN KEY (material_id)
        REFERENCES material (material_id),
    CONSTRAINT chk_material_request_item_quantity_positive CHECK (requested_quantity > 0)
);

CREATE INDEX idx_material_request_seminar_id
    ON material_request (seminar_id);

CREATE INDEX idx_material_request_contract_id
    ON material_request (contract_id);

CREATE INDEX idx_material_request_status
    ON material_request (shipment_status);

CREATE INDEX idx_material_request_item_material_id
    ON material_request_item (material_id);
